const initState = {
    inCart: [],
    products: [
        {
            id: 0,
            title: 'Blue Jacket',
            desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
            price: 129,
            category: 'clothes',
            stock: 8,
            imgUrl: require('../assets/images/blue-shirt.png').default,
            isFav: false,
            rating: 4.5,
        },
        {
            id: 5,
            title: 'Honda Super Cub C125',
            desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
            price: 1000,
            category: 'motorcycle',
            stock: 7,
            imgUrl: require('../assets/images/honda.png').default,
            isFav: false,
            rating: 2.5,
        },
        {
            id: 2,
            title: ' Zanzibar Gem desk plants',
            desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
            price: 320,
            category: 'plants',
            stock: 15,
            imgUrl: require('../assets/images/plant.png').default,
            isFav: false,
            rating: 4.0,
        },
        {
            id: 1,
            title: 'Dell XPS 15 9550',
            desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
            price: 1210,
            category: 'computer',
            stock: 10,
            imgUrl: require('../assets/images/dell.png').default,
            isFav: false,
            rating: 3.0,
        },
        {
            id: 3,
            title: 'Red hoodie',
            desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
            price: 229,
            category: 'clothes',
            stock: 12,
            imgUrl: require('../assets/images/red-hoodie.png').default,
            isFav: false,
            rating: 2.5,
        },
        {
            id: 4,
            title: 'Shoes',
            desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
            price: 429,
            category: 'clothes',
            stock: 7,
            imgUrl: require('../assets/images/shoes.png').default,
            isFav: false,
            rating: 2.5,
        },
    ]
}

export default initState